# Generated by Django 3.1.7 on 2021-04-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banquet',
            options={'verbose_name': 'Банкет', 'verbose_name_plural': 'Банкеты'},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Еда', 'verbose_name_plural': 'Еда'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Музыка', 'verbose_name_plural': 'Музыка'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
    ]
