# Generated by Django 3.1.7 on 2021-04-25 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0003_auto_20210425_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(default=datetime.date),
        ),
    ]
