# Generated by Django 3.1.7 on 2021-04-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0004_auto_20210425_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birthday',
        ),
    ]
