# Generated by Django 3.1.7 on 2021-04-30 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='banquet',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 30)),
        ),
    ]
