# Generated by Django 3.1.7 on 2021-04-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0009_foodcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banquet.foodcategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banquet.foodcategory'),
        ),
    ]
