# Generated by Django 3.1.7 on 2021-04-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0010_auto_20210430_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='banquet',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='banquet',
            name='food',
        ),
        migrations.AddField(
            model_name='banquet',
            name='food',
            field=models.ManyToManyField(default=0, to='banquet.Food'),
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
