# Generated by Django 3.1.7 on 2021-04-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banquet', '0011_auto_20210430_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquet',
            name='food',
            field=models.ManyToManyField(null=True, related_name='banquets', to='banquet.Food'),
        ),
    ]
